development:
  adapter: postgresql
  encoding: unicode
  database: micro_development
  pool: 5
  username: matt
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: micro_test
  pool: 5
  username: matt
  password:
